controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute

app_docker:
    controller: App\Controller\DockerController::index
    path: '/api/docker'
    methods: ['POST']